url: "https://haruto-md.github.io"
repository: "haruto-md/websiteTemp"

locale: "ja-JP"
title: 九州大学医学部情報研
collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /posts/:name/