url: "https://qumiclub.github.io"
baseurl: "/club-welcome-page"
repository: "qumiclub/club-welcome-page"

locale: "ja-JP"
title: 九州大学医学部情報研
name: "九州大学医学部情報研"
description: "九州大学医系サークル・九州大学医学部情報研です、病院キャンパスでKaggleや統計解析の勉強会等の活動を行っています"
collections:
  pages:
    output: true
    permalink: /:name/
kramdown:
  input: GFM
  toc_levels: 1..3
  auto_ids: true